baseURL = 'https://blog.chrislewis.au'
languageCode = 'en-au'
title = "Chris' Blog"
theme = 'hugo-bearblog'
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
hideMadeWithLine = true
description = "Various ramblings"
enablePostNavigator = true

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    codeFences = true